#!/bin/bash
main() {
    clonePath=$("pwd")

    ln -sf "$clonePath/.bash_profile" "$HOME/.bash_profile"
    ln -sf "$clonePath/.eslintrc.yaml" "$HOME/.eslintrc.yaml"
    ln -sf "$clonePath/.gitignore" "$HOME/.gitignore"
    ln -sf "$clonePath/.gitconfig" "$HOME/.gitconfig"
    ln -sf "$clonePath/.tmux.conf" "$HOME/.tmux.conf"
    ln -sf "$clonePath/.vimrc" "$HOME/.vimrc"
    ln -sf "$clonePath/.vim" "$HOME"
    ln -sf "$clonePath/.ssh" "$HOME"

    sh keybindings.sh

    # disable smart dashes globally
    defaults write 'Apple Global Domain' NSAutomaticDashSubstitutionEnabled 0
    # disable smart quotes globally
    # defaults write 'Apple GLobal Domain' NSAutomaticQuoteSubstitutionEnabled 0

    echo "Now open OSX Terminal preferences and import base16-ocean.dark.terminal"
}

main;
