#!/bin/bash
main() {
    clonePath=$("pwd")

    ln -sf "$clonePath/.bash_profile" "$HOME/.bash_profile"
    # prevent last login message (goo.gl/nIHUaa)
    ln -sf "$clonePath/.hushlogin" "$HOME/.hushlogin"
    ln -sf "$clonePath/.eslintrc.yaml" "$HOME/.eslintrc.yaml"
    ln -sf "$clonePath/.gitignore" "$HOME/.gitignore"
    ln -sf "$clonePath/.gitconfig" "$HOME/.gitconfig"
    ln -sf "$clonePath/.tmux.conf" "$HOME/.tmux.conf"
    ln -sf "$clonePath/.vimrc" "$HOME/.vimrc"
    ln -sf "$clonePath/.vim" "$HOME"
    ln -sf "$clonePath/.bin" "$HOME/.bin"
    ln -sf "$clonePath/.ssh" "$HOME"

    sh keybindings.sh

    # disable smart dashes globally
    defaults write 'Apple Global Domain' NSAutomaticDashSubstitutionEnabled 0
    # disable smart quotes globally
    # defaults write 'Apple GLobal Domain' NSAutomaticQuoteSubstitutionEnabled 0

    # disable terminal 'Marks' feature (goo.gl/HJEodP)
    # or simply hide it through menu > view> hide marks
    # defaults write com.apple.Terminal AutoMarkPromptLines -int 0
    echo "Now open OSX Terminal preferences and import base16-ocean.dark.terminal"
}

main;
